### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [ZorinOS/zorin-connect-android#1]
Since Zorin Connect is open source can you post it on F-droid (https://f-droid.org/ ) to.
I won't mind downloading it from a trusted source.

Thank you

**Comment by ArtyomZorin** [comment]
Thanks for the suggestion! We have added this to our roadmap, so we will submit the app to F-droid before the stable release of Zorin OS 15.

**Comment by ArtyomZorin** [comment]
I've created a [merge request](https://gitlab.com/fdroid/fdroiddata/merge_requests/4701) on F-Droid's data repository. Now waiting on approval for inclusion into F-Droid.

**Comment by Ashutosh-Kukreti** [comment]
Thank you

**Comment by OffifialMITX** [comment]
It is in the F-Droid repo by now, but it won't show up on the frontpage, (maybe not only) because no screenshots are included.
