### ISSUE TITLE
Zorin Connect from command line

### ISSUE THREAD

**Issue by ntaraujo** [ZorinOS/zorin-connect-android#10]
Is there any way to run Zorin Connect from the command line like KDE Connect does?

I could save a screenshot on my phone with `kdeconnect-cli`:
```
file=/tmp/$(hostname)_$(date "+%Y%m%d_%H%M%S").png; spectacle -bo "${file}" && while ! [ -f "${file}" ]; do sleep 0.5; done && kdeconnect-cli -d $(kdeconnect-cli -a --id-only) --share "${file}"
```

If it is not possible, are there any plans to implement this?

**Comment by ArtyomZorin** [comment]
You can use the Zorin Connect CLI by entering this command with parameters:
`/usr/share/gnome-shell/extensions/zorin-connect@zorinos.com/service/daemon.js`

To find out which parameters are available, you can enter this help command:
`/usr/share/gnome-shell/extensions/zorin-connect@zorinos.com/service/daemon.js --help`

It should be possible to take a screenshot and send it to your phone using this command, replacing "**DEVICE_ID**" below with your phone's ID in Zorin Connect (which you can find using [dconf Editor](https://wiki.gnome.org/Apps/DconfEditor) > /org/gnome/shell/extensions/zorin-connect/devices):
`file=/tmp/$(hostname)_$(date "+%Y%m%d_%H%M%S").png; gnome-screenshot -f "${file}" && gapplication action org.gnome.Shell.Extensions.ZorinConnect device "('DEVICE_ID', 'shareFile', true, <('${file}', false)>)"`
