### ISSUE TITLE
Persistent Indicator

### ISSUE THREAD

**Issue by asitgujar2** [ZorinOS/zorin-connect-android#13]
If its possibel to hide Persistent Indicator notification automatically whenever it's not connected. It will be very helpful.

**Comment by ArtyomZorin** [comment]
You can disable the persistent indicator by opening the app menu > Settings > Persistent notification and switching off the "Persistent indicator" option.

**Comment by asitgujar2** [comment]
> You can disable the persistent indicator by opening the app menu > Settings > Persistent notification and switching off the "Persistent indicator" option.

Ya, that's ok but, the persistent notification is really handy while working cross device, and turning permantly on  and off, while not in use and while using is not really handy. And i do work mostly cross device.

So, if possible, let's say auto hide while not in use can be handy.
