### ISSUE TITLE
Not connecting to mobile

### ISSUE THREAD

**Issue by adhilvpd** [ZorinOS/zorin-connect-android#18]
I can't connect my mobile device with the Zorin Connect. I wanted to know that whether the feature is under development or is it having problems just for me. The devices don't show neither in my Mobile phone nor on Laptop.

It's just showing " searching for devices...". I dont have any problems regarding Bluetooth as I can connect the laptop to my mobile through Bluetooth.

**Comment by ArtyomZorin** [comment]
Hello. Please make sure that your computer and phone are connected to the same Wi-Fi network before pairing with Zorin Connect.

Closing, as this is a support query instead of an issue report.
