### ISSUE TITLE
Please Add Feature "Hide notificaton on lockscreen"

### ISSUE THREAD

**Issue by Agroithien** [ZorinOS/zorin-connect-android#22]
Please add this option because it changes my lock screen look and also feel no one uses the app on the lock screen please please please add the feature

**Comment by ArtyomZorin** [comment]
You can hide the Zorin Connect notification by hiding its persistent notification:
1. Launch the Zorin Connect app
2. Open the menu on the left and tap "Settings"
3. Tap the "Persistent notification" item
4. Switch off the "Persistent indicator" item

**Comment by Agroithien** [comment]
turning off the Persistent indicator is also hiding notifications on the unlocked screen, I just want to hide notifications from the lock screen.

**Comment by ArtyomZorin** [comment]
You can hide the Zorin Connect notification only on the lock screen by following these steps:
1. Launch the Zorin Connect app
2. Open the menu on the left and tap "Settings"
3. Tap the "Persistent notification" item
4. Switch on the "Persistent indicator" item
5. Tap the "Persistent indicator" item (not its switch button) to view its settings page
6. Open the "Advanced" section
7. Tap "Lock screen" and select "Don't show notifications at all"

**Comment by Agroithien** [comment]
Thank You............ THANK YOU VERY MUCH FOR THIS, OMG I feel so dumb, I appreciate all the time you took to solve the issue...
