### ISSUE TITLE
Material Icon

### ISSUE THREAD

**Issue by WreckingBANG** [ZorinOS/zorin-connect-android#25]
Will there be a Material Icon?

**Comment by ArtyomZorin** [comment]
Unfortunately I don't understand your question. You can find the app's icon in different resolutions in the `/res/mipmap` folders of this repo.

**Comment by WreckingBANG** [comment]
> Unfortunately I don't understand your question. You can find the app's icon in different resolutions in the `/res/mipmap` folders of this repo.

Ok no Problem i will do a Pull Request.

**Comment by WreckingBANG** [comment]
It it a Icon that matches your background. It is Part of Androids Material You and can be added with a extra Line in the ic_launcher.xml

`    <monochrome android:drawable="@drawable/<your_appicon_xml_name>" />`

![Screenshot_20230116_172601_One UI Home](https://user-images.githubusercontent.com/86848811/212725769-d8d605f1-7fad-4784-9b3b-df5b25218fa5.jpg)

Please add it so that all my icons match each other.

PS: Love your distro! I daily drove it for a Week and had no issues!

**Comment by WreckingBANG** [comment]
Closed with #26
