### ISSUE TITLE
Help with message syncing

### ISSUE THREAD

**Issue by kristof-linux** [ZorinOS/zorin-connect-android#29]
Hello,
Everything works fine, but in the message pane i only see very old messages, most conservations also contains only one or no messages...very strange. I can send an sms, but it's grey when i send a new message and it's also not saved in the left pane...
I have a samsung A53.
Can anybody help please?
Thx,
Kristof

![image](https://github.com/ZorinOS/zorin-connect-android/assets/58733661/0b93f1ef-39ad-49bb-9e66-657a0577788a)

**Comment by ArtyomZorin** [comment]
Closing as this is a support query.

To get support from the community, we would recommend you to post your query on our forum: https://forum.zorin.com/
