### ISSUE TITLE
When notifications are read on one device, it should be read on all of them

### ISSUE THREAD

**Issue by nicolasmaia** [ZorinOS/zorin-connect-android#6]
If I get a notification on both my phone and my laptop, as soon as I click on or clear the notifications on one device, the other should also get rid of the notifications.

**Comment by ArtyomZorin** [comment]
It is currently possible to dismiss your phone's notifications from your computer by pressing the "X" button for the the specific notification in the notifications menu on the desktop (visible after clicking the panel clock).
Please make sure that you are using a stable Wi-Fi connection to ensure this happens smoothly and quickly between your devices.
